baseURL = 'https://isilab-utalca.github.io/isilab-website/'
languageCode = 'en-us'
title = 'ISILAB'
subtitle = 'UTAL'
theme = 'PaperMod'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false

[languages]
  [languages.en]
      languageName = "English"
      languageCode = "en"
    weight = 1
  [languages.es]
    languageName = "Espanol"
    languageCode = "es"
    weight = 2


[taxonomies]
  genre = 'genres'
  tag = 'tags'
  category = 'categories'


[params]
  mainSections = ["posts", "projects", "documentation"]
  intro = true
  headline = "Interactive Software Intelligence Laboratory"
  description = "Laboratorio de software interactivo inteligente de la universidad de Talca."
  github = "https://github.com/ISILab-Utalca"
  twitter = "x.com/idvrv"
  email = "nbarriga@utalca.cl"
  opengraph = true
  shareTwitter = true
  dateFormat = "Mon, Jan 2, 2006"
  hideFooter = false
  video =   "https://youtu.be/smIRgKcAXoY?si=kTdGSH9qTlSYHzQa"
  defaultTheme = "dark"


  ShowReadingTime = true
  #ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true 
    
  [params.cover]
    responsiveImages = false

  [params.assets]
    favicon = "images/favicon.ico"
    favicon16x16 = "images/favicon16x16.png"
    favicon32x32 = "images/favicon32x32.png"
    apple_touch_icon = "images/apple-touch-icon.png"


[params.homeInfoParams]
  logo = "../assets/images/isilab_box_logo_1x.png"
  title = "Interactive Software Intelligence Laboratory"
  content = "Laboratorio de software interactivo inteligente de la universidad de Talca."
  TileImageDark = "images/blk_isometric_tile.png"
  TileImageLight = "images/wth_isometric_tile.png"


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "posts/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "projects/"
    weight = 20

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "documentation/"
    weight = 30

  [[menu.main]]
    identifier = "api"
    name = "API"
    url = "api/"
    weight = 32

  [[menu.main]]
    identifier = "about_us"
    name = "About Us"
    url = "about/"
    weight = 35

  # [[menu.main]]
  #   identifier = "utal"
  #   name = "Utalca"
  #   url = "https://admision.utalca.cl/carreras/ingenieria-en-desarrollo-de-videojuegos-y-realidad-virtual/"
  #   weight = 100

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'


[outputs]
  home = [ "HTML", "RSS", "JSON" ]


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
    
      [markup.goldmark.parser.attribute]
        block = true
        title = true
