baseURL = 'https://isilab.utalca.cl/'
languageCode = 'en-us'
title = 'ISILAB'
subtitle = 'UTAL'
#theme = "mostafa-hugo-theme"
theme = 'PaperMod'

[taxonomies]
  genre = 'genres'
  tag = 'tags'
  category = 'categories'


  [Params]
    mainSections = ["posts", "projects"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

    hideFooter = false

[Permalinks]
    post = "/:filename/"
    