baseURL = 'https://isilab.utalca.cl/'
languageCode = 'en-us'
title = 'ISILAB'
#theme = "mostafa-hugo-theme"
theme = 'PaperMod'

[taxonomies]
  genre = 'genres'
  tag = 'tags'
  category = 'categories'